# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'autoClicker.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form(object):
    def setupUi(self, form):
        form.setObjectName("form")
        form.setWindowModality(QtCore.Qt.NonModal)
        form.resize(315, 94)
        form.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.BtnSave = QtWidgets.QPushButton(form)
        self.BtnSave.setGeometry(QtCore.QRect(10, 50, 93, 28))
        self.BtnSave.setCheckable(True)
        self.BtnSave.setObjectName("BtnSave")
        self.BtnStart = QtWidgets.QPushButton(form)
        self.BtnStart.setEnabled(False)
        self.BtnStart.setGeometry(QtCore.QRect(130, 50, 93, 28))
        self.BtnStart.setCheckable(True)
        self.BtnStart.setAutoDefault(False)
        self.BtnStart.setDefault(False)
        self.BtnStart.setFlat(False)
        self.BtnStart.setObjectName("BtnStart")
        self.LneToggleKey = QtWidgets.QLineEdit(form)
        self.LneToggleKey.setGeometry(QtCore.QRect(122, 10, 31, 22))
        self.LneToggleKey.setMaxLength(1)
        self.LneToggleKey.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.LneToggleKey.setReadOnly(False)
        self.LneToggleKey.setObjectName("LneToggleKey")
        self.LbInput = QtWidgets.QLabel(form)
        self.LbInput.setGeometry(QtCore.QRect(10, 10, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.LbInput.setFont(font)
        self.LbInput.setObjectName("LbInput")

        self.retranslateUi(form)
        self.BtnSave.clicked["bool"].connect(self.BtnStart.setEnabled)  # type: ignore
        self.BtnStart.clicked["bool"].connect(self.BtnSave.setDisabled)  # type: ignore
        self.BtnSave.clicked["bool"].connect(self.LneToggleKey.setDisabled)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(form)

    def retranslateUi(self, form):
        _translate = QtCore.QCoreApplication.translate
        form.setWindowTitle(_translate("form", "Auto Clicker"))
        self.BtnSave.setText(_translate("form", "Save"))
        self.BtnStart.setText(_translate("form", "Start"))
        self.LbInput.setText(_translate("form", "Set Toggle Key:"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    form = QtWidgets.QWidget()
    ui = Ui_form()
    ui.setupUi(form)
    form.show()
    sys.exit(app.exec_())
