# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'autoClicker.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form(object):
    def setupUi(self, form):
        form.setObjectName("form")
        form.setWindowModality(QtCore.Qt.NonModal)
        form.resize(300, 125)
        form.setMinimumSize(QtCore.QSize(300, 125))
        form.setMaximumSize(QtCore.QSize(300, 125))
        form.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("app.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        form.setWindowIcon(icon)
        form.setAutoFillBackground(False)
        form.setStyleSheet("")
        self.BtnSave = QtWidgets.QPushButton(form)
        self.BtnSave.setGeometry(QtCore.QRect(10, 60, 131, 28))
        self.BtnSave.setStyleSheet("")
        self.BtnSave.setCheckable(True)
        self.BtnSave.setFlat(False)
        self.BtnSave.setObjectName("BtnSave")
        self.BtnStart = QtWidgets.QPushButton(form)
        self.BtnStart.setEnabled(False)
        self.BtnStart.setGeometry(QtCore.QRect(160, 60, 131, 28))
        self.BtnStart.setCheckable(True)
        self.BtnStart.setAutoDefault(False)
        self.BtnStart.setDefault(False)
        self.BtnStart.setFlat(False)
        self.BtnStart.setObjectName("BtnStart")
        self.LneToggleKey = QtWidgets.QLineEdit(form)
        self.LneToggleKey.setGeometry(QtCore.QRect(191, 15, 41, 31))
        self.LneToggleKey.setMaxLength(1)
        self.LneToggleKey.setAlignment(QtCore.Qt.AlignCenter)
        self.LneToggleKey.setReadOnly(False)
        self.LneToggleKey.setObjectName("LneToggleKey")
        self.LbInput = QtWidgets.QLabel(form)
        self.LbInput.setGeometry(QtCore.QRect(50, 10, 141, 41))
        self.LbInput.setObjectName("LbInput")
        self.horizontalLayoutWidget = QtWidgets.QWidget(form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 100, 281, 21))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LblFooterBuild = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.LblFooterBuild.setObjectName("LblFooterBuild")
        self.horizontalLayout.addWidget(self.LblFooterBuild)
        self.LblFooter = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.LblFooter.setFont(font)
        self.LblFooter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LblFooter.setObjectName("LblFooter")
        self.horizontalLayout.addWidget(self.LblFooter)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 3)

        self.retranslateUi(form)
        self.BtnSave.clicked['bool'].connect(self.BtnStart.setEnabled) # type: ignore
        self.BtnStart.clicked['bool'].connect(self.BtnSave.setDisabled) # type: ignore
        self.BtnSave.clicked['bool'].connect(self.LneToggleKey.setDisabled) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(form)

    def retranslateUi(self, form):
        _translate = QtCore.QCoreApplication.translate
        form.setWindowTitle(_translate("form", "Auto Clicker"))
        self.BtnSave.setText(_translate("form", "Save"))
        self.BtnStart.setText(_translate("form", "Start"))
        self.LbInput.setText(_translate("form", "Set Toggle Key:"))
        self.LblFooterBuild.setText(_translate("form", "build v1.0.0"))
        self.LblFooter.setText(_translate("form", "   developed by WolfGear.tech"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    form = QtWidgets.QWidget()
    ui = Ui_form()
    ui.setupUi(form)
    form.show()
    sys.exit(app.exec_())
