# This is a basic workflow to help you get started with Actions

name: Create Executable file

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the "main" branch
  pull_request:
    types: [ "closed" ]
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Run pyinstaller
        run: |
          pyinstaller -F -n "AutoClicker" main.pyw

      - name: Upload file
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "/home/runner/work/Auto-Clicker/Auto-Clicker/dist/AutoClicker"
          overwrite: true
          draft: false
          tag_name: ${{ github.event.pull_request.title }}
